components:

  instrumentation/opentelemetry-instrumentation-aiohttp-client:
    - herin049

  instrumentation/opentelemetry-instrumentation-aiokafka:
    - dimastbk

  instrumentation/opentelemetry-instrumentation-asyncclick:
    - jomcgi

  instrumentation/opentelemetry-instrumentation-asyncio:
    - bourbonkk

  instrumentation/opentelemetry-instrumentation-botocore:
    - lukeina2z
    - yiyuan-he

  instrumentation/opentelemetry-instrumentation-pymssql:
    - guillaumep

  instrumentation/opentelemetry-instrumentation-urllib:
    - shalevr

  instrumentation/opentelemetry-instrumentation-urllib3:
    - shalevr

  instrumentation-ai/:
    - karthikscale3
    - lmolkova
    - lzchen
    - gyliu513
    - nirga
    - alizenhom
    - codefromthecrypt

  processor/opentelemetry-processor-baggage:
    - codeboten

  propagator/opentelemetry-propagator-aws-xray:
    - jj22ee

  sdk-extension/opentelemetry-sdk-extension-aws:
    - srprash
    - jj22ee

  util/opentelemetry-util-genai:
    - DylanRussell
    - keith-decker

  instrumentation-ai/frameworks/opentelemetry-instrumentation-langchain:
    - zhirafovod
    - wrisa

  instrumentation-ai/agents/opentelemetry-instrumentation-openai-agents-v2:
    - nagkumar91

  instrumentation-ai/llm-providers/opentelemetry-instrumentation-anthropic:
    - vasantteja
